### ISSUE TITLE
Part 1 changes for aws-amplify 3

### ISSUE THREAD

**Issue by kenklin** [mlomboglia/react-amplify#1]
Thanks for the clearly written articles.  I tried Part 1 today and my resulting login screen matched the one described here - https://stackoverflow.com/questions/61159622/login-form-implemented-with-amplify-is-not-applied-styling ...

![image](https://user-images.githubusercontent.com/2544601/82084158-db8fba80-96b8-11ea-84da-033a044c3969.png)

I was able to correct it using kjmczk's suggestion ...
> Try using @aws-amplify/ui-react instead of aws-amplify-react.
> 
> `import { withAuthenticator } from '@aws-amplify/ui-react';`

Looking at your [package.json](https://github.com/mlomboglia/react-amplify/blob/master/part-1-authentication/package.json), I am guessing it is because your `aws-amplify` is version 2, while as of 5/15/20, my `npm install aws-amplify` is version 3.0.11 (I have also installed `@aws-amplify/ui-react`).
```
"dependencies": {
    "@aws-amplify/ui-react": "^0.2.6",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "aws-amplify": "^3.0.11",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"
  }, 
```

I am posting this in case others also experience the same version 3 issue while following your article.

**Comment by tomcavanaugh** [comment]
Though referenced above, it wasn't clear me to that I also needed to install additional packages/modules.

`npm install @aws-amplify/ui-react`

**Comment by mlomboglia** [comment]
Thanks @tomcavanaugh and @kenklin, I have updated the code to use the new Amplify version 3. Everything should work now.
